import { z } from "zod";
export declare const ZODSCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    phone: z.ZodString;
    country: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
}>;
export type ZODSCHEMA = z.infer<typeof ZODSCHEMA>;
export declare const IDZODSCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    phone: z.ZodString;
    country: z.ZodDefault<z.ZodString>;
    id: z.ZodNumber;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    id?: number;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    id?: number;
}>;
export type IDZODSCHEMA = z.infer<typeof IDZODSCHEMA>;
export declare const UUIDSCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    phone: z.ZodString;
    country: z.ZodDefault<z.ZodString>;
    uuid: z.ZodString;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    uuid?: string;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    uuid?: string;
}>;
export type UUIDSCHEMA = z.infer<typeof UUIDSCHEMA>;
export declare const WITHNAMESCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    phone: z.ZodString;
    country: z.ZodDefault<z.ZodString>;
    name: z.ZodString;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    name?: string;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    name?: string;
}>;
export type WITHNAMESCHEMA = z.infer<typeof WITHNAMESCHEMA>;
export declare const PHONEOPTIONALSCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    country: z.ZodDefault<z.ZodString>;
    name: z.ZodString;
    phone: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    country?: string;
    name?: string;
    phone?: string;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    country?: string;
    name?: string;
    phone?: string;
}>;
export type PHONEOPTIONALSCHEMA = z.infer<typeof PHONEOPTIONALSCHEMA>;
export declare const ONLYPHONEOPTIONALSCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    country: z.ZodDefault<z.ZodString>;
    phone: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    country?: string;
    phone?: string;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    country?: string;
    phone?: string;
}>;
export type ONLYPHONEOPTIONALSCHEMA = z.infer<typeof ONLYPHONEOPTIONALSCHEMA>;
export declare const PHONEOPTIONALWITHUUIDSCHEMA: z.ZodObject<{
    full_name: z.ZodString;
    company_name: z.ZodOptional<z.ZodString>;
    street_one: z.ZodString;
    street_two: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    zip: z.ZodString;
    state: z.ZodString;
    phone: z.ZodOptional<z.ZodString>;
    country: z.ZodDefault<z.ZodString>;
    name: z.ZodString;
    uuid: z.ZodString;
}, "strip", z.ZodTypeAny, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    name?: string;
    uuid?: string;
}, {
    full_name?: string;
    company_name?: string;
    street_one?: string;
    street_two?: string;
    city?: string;
    zip?: string;
    state?: string;
    phone?: string;
    country?: string;
    name?: string;
    uuid?: string;
}>;
export type PHONEOPTIONALWITHUUIDSCHEMA = z.infer<typeof PHONEOPTIONALWITHUUIDSCHEMA>;
//# sourceMappingURL=address.d.ts.map