CREATE TABLE `batchs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`uuid` text NOT NULL,
	`user_id` integer NOT NULL,
	`status_message` text,
	`status_label` text DEFAULT 'processing' NOT NULL,
	`status_refund` integer DEFAULT false NOT NULL,
	`is_downloaded` integer DEFAULT false NOT NULL,
	`pdf_r2_link` text,
	`sender_full_name` text NOT NULL,
	`sender_company_name` text,
	`sender_street_one` text NOT NULL,
	`sender_street_two` text,
	`sender_city` text NOT NULL,
	`sender_zip` text NOT NULL,
	`sender_state` text NOT NULL,
	`sender_country` text NOT NULL,
	`recipient` text NOT NULL,
	`type` text NOT NULL,
	`type_label` text NOT NULL,
	`type_value` text NOT NULL,
	`weight_unit` text NOT NULL,
	`package_id` integer,
	`package_uuid` text,
	`package_name` text,
	`package_width` integer NOT NULL,
	`package_height` integer NOT NULL,
	`package_length` integer NOT NULL,
	`package_weight` integer NOT NULL,
	`cost_user` integer NOT NULL,
	`cost_reseller` integer NOT NULL,
	`shipping_date` text NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP,
	`updated_at` text DEFAULT CURRENT_TIMESTAMP
);
--> statement-breakpoint
ALTER TABLE labels ADD `batch_uuid` text;